server {
    listen 80;
    server_name localhost;

    # 1. 静态图片处理 (Nginx 直接读硬盘，不走 Java)
    location /uploads/ {
        root /usr/share/nginx/html;
        expires 30d; # 设置浏览器缓存
    }

    # 2. API 转发 (转发给 Spring Boot 8080)
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. 前端 SPA 处理
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

